---
- name: Configure APT Elastic repositories
  hosts: all
  become: true
  tasks:
  - name: Get Elastic key
    ansible.builtin.apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
  - name: Add Elastic repository
    ansible.builtin.apt_repository:
      repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
      state: present